const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current='playground',channel='chat',state=null,documents=[],result=null,job=null,running=false,question='When is my payment due?';
const names={'conversation-gateway':'Gateway','conversation-service':'Conversation','stt-service':'Speech recognition','knowledge-service':'Knowledge retrieval','llm-service':'Response generation','tts-service':'Speech synthesis'};
const pageNames={overview:'Overview',playground:'Agent playground',conversations:'Conversations',voice:'Voice test',knowledge:'Knowledge',status:'System status',lab:'Demo lab'};
const theme=localStorage.getItem('converselab-theme')||'light';document.documentElement.dataset.theme=theme;
function themeLabel(){$('#themeToggle').textContent=document.documentElement.dataset.theme==='light'?'☾ Dark':'☀ Light';$('#themeToggle').setAttribute('aria-label','Switch to '+(document.documentElement.dataset.theme==='light'?'dark':'light')+' theme')}themeLabel();
async function api(path,data){const r=await fetch('/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok&&!v.request_id)throw Error(v.error||'Request failed');return v}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function head(title,sub,kicker='AGENT STUDIO'){return `<div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${sub}</p></div><span class="badge">DEVELOPMENT WORKSPACE</span></div>`}
function pipeline(){const stages=channel==='voice'?['stt-service','knowledge-service','llm-service','tts-service']:['knowledge-service','llm-service'];const spans=job?.pipeline||result?.spans||[];return `<p class="pipeline-note">Measured service calls for this request. Chat skips the speech stages.</p><div>${stages.map((name,i)=>{const span=spans.find(s=>s.service===name),active=running&&job?.stage===name&&!span;return `<div class="stage ${span?.status|| (active?'running':'')}"><span class="stage-icon">${span?span.status==='ok'?'✓':'!':active?'…':i+1}</span><div><strong>${names[name]}</strong><small>${span?span.status==='ok'?'HTTP '+(span.status_code||200)+' · completed':'HTTP '+span.status_code+' · '+esc(span.error):active?'Request in progress':'Waiting for request'}</small></div><time>${span?span.ms+' ms':'—'}</time></div>`}).join('')}</div><div><div class="pipeline-total"><span>Total response time</span><b>${result?(result.latency/1000).toFixed(2)+' s':'—'}</b></div><div class="trace-details">${result||job?`Conversation: ${esc((result||job).conversation_id)}<br>Request: ${esc((result||job).request_id)}<br>Trace: ${esc((result||job).trace_id)}`:'Identifiers appear after you send a request.'}</div><div class="provider-note">SIMULATED EXTERNAL PROVIDERS<br>STT receives typed speech input. LLM uses retrieved demo context. TTS simulates speech delivery; no audio recording or playback. HTTP requests and outcomes are real.</div></div>`}
function playground(){return head(channel==='voice'?'Every voice. Every step.':'Great conversations start here.','Test your support agent and follow every service along the way.')+`<div class="agent-ribbon"><div class="agent-icon">✧</div><div><h2>Customer Support Assistant</h2><small>Knowledge-grounded support · prompt ${esc(state?.config.prompt_version||'—')}</small></div><span class="badge ${state?.services.some(s=>!s.healthy)?'amber':''}">${state?.services.some(s=>!s.healthy)?'DEPENDENCY DEGRADED':'SERVICES ONLINE'}</span></div><div class="playground"><section class="card"><div class="card-head"><h2>Conversation preview</h2><div class="channels"><button data-channel="chat" class="${channel==='chat'?'active':''}" ${running?'disabled':''}>Chat</button><button data-channel="voice" class="${channel==='voice'?'active':''}" ${running?'disabled':''}>Voice</button></div></div><div class="conversation-space" id="conversationSpace">${conversationHTML()}</div><form class="composer" id="conversationForm"><label for="question" class="eyebrow">${channel==='voice'?'SIMULATED SPOKEN INPUT':'YOUR MESSAGE'}</label><textarea id="question" maxlength="2000" required placeholder="Ask your support agent a question…" ${running?'disabled':''}>${esc(question)}</textarea><div class="composer-row"><small>${channel==='voice'?'Typed input → STT → RAG → LLM → TTS':'Grounded in 4 local knowledge documents'}</small><button class="primary" id="sendButton" ${running?'disabled':''}>${running?'Request in progress…':channel==='voice'?'Run voice test ↗':'Send message ↗'}</button></div></form></section><aside class="card pipeline"><div class="card-head"><h2>Live request pipeline</h2><span class="badge ${result&&!result.ok?'red':''}" id="pipelineBadge">${running?'RUNNING':result?result.ok?'COMPLETED':'FAILED':'READY'}</span></div><div class="card-body" id="pipelineBody">${pipeline()}</div></aside></div>`}
function conversationHTML(){if(!result&&!running)return `<div class="empty-chat"><span class="star">✧</span><h3>A helpful answer is one message away.</h3><p>Try a billing, order, or support question.<br>See the response and the evidence behind it.</p><div class="questions"><button data-question="When is my payment due?">Payment due date ↗</button><button data-question="Where is my order?">Track an order ↗</button><button data-question="How do I request a refund?">Return policy ↗</button></div></div>`;return `<div class="bubble user"><small>YOU · ${channel.toUpperCase()}</small>${esc(result?.text||question)}</div>${running?'<div class="bubble"><small>ASSISTANT</small>Waiting for the actual service response…</div>':`<div class="bubble ${result.ok?'':'error'}"><small>${result.ok?'SUPPORT ASSISTANT':channel==='voice'&&result.answer?'TEXT GENERATED · VOICE DELIVERY FAILED':'CONVERSATION FAILED'}</small>${esc(result.answer||'The support agent could not complete this request. Please try again after the service recovers.')}${!result.ok?`<p class="failure">${esc(result.error)}</p>`:''}<div>${(result.citations||[]).map(c=>`<button class="citation" data-document="${c.id}">${esc(c.id)} · ${esc(c.title)}</button>`).join('')}</div>${result.ok&&channel==='voice'?'<p class="muted">Simulated speech delivery completed. No audio was generated.</p>':''}</div>`}`}
function overview(){const m=state?.metrics;return head('Your conversations, in focus.','A clear view of channel health and customer experience.','WORKSPACE OVERVIEW')+`<div class="stats">${[['Conversations',m?.total_requests||0],['Chat success',(m?.channels.chat.success_rate||0)+'%'],['Voice success',(m?.channels.voice.success_rate||0)+'%'],['Response p95',(m?.p95||0)+' ms']].map(([k,v])=>`<div class="stat"><small>${k}</small><b>${v}</b></div>`).join('')}</div><div class="card"><div class="card-body"><span class="eyebrow">YOUR SUPPORT AGENT</span><h2>One agent. Two customer channels.</h2><p class="notice">Chat uses Knowledge → LLM. Voice adds STT and TTS. Each stage runs behind its own real HTTP endpoint, so a voice-only dependency failure can leave chat working.</p><button class="primary" data-nav="playground">Open agent playground ↗</button></div></div><div class="provider-note">Success percentages describe recent requests. No requests does not establish service health.</div>`}
function history(){const rows=(state?.events||[]).slice().reverse();return head('Every conversation has a story.','Recent runtime requests, including fresh IncidentCommander verification.','CONVERSATION HISTORY')+`<div class="card table-wrap"><table><thead><tr><th>CONVERSATION</th><th>CHANNEL</th><th>OUTCOME</th><th>LATENCY</th><th>DETAILS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.conversation_id)}<small>${new Date(r.timestamp*1000).toLocaleTimeString()}</small></td><td>${esc(r.channel)}</td><td><span class="badge ${r.ok?'':'red'}">${r.ok?'COMPLETED':'FAILED'}</span></td><td>${r.latency} ms</td><td><button data-result="${r.request_id}">Inspect trace ↗</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Your first conversation will appear here.</div>'}</div>`}
function knowledge(){return head('Helpful answers need good context.','Four seeded documents, retrieved by a deterministic keyword matcher.','KNOWLEDGE LIBRARY')+`<div class="grid">${documents.map(d=>`<article class="card doc"><div class="card-body"><small>${esc(d.id)} · SEED DOCUMENT</small><h2 style="margin-top:12px">${esc(d.title)}</h2><p>${esc(d.text)}</p><span class="badge">LOCAL KNOWLEDGE</span></div></article>`).join('')}</div><div class="notice">This is lightweight retrieval over demo documents. It does not use embeddings, a vector database, or real customer account data.</div>`}
function systemStatus(){return head('See the whole conversation stack.','Service health and measured activity from actual HTTP requests.','SYSTEM STATUS')+`<div class="card table-wrap"><table><thead><tr><th>SERVICE</th><th>HEALTH</th><th>MEASURED LATENCY</th><th>ERROR RATE</th><th>MODE</th></tr></thead><tbody>${(state?.services||[]).map(s=>{const m=state.metrics.services[s.service];return `<tr><td>${esc(names[s.service])}<small>${esc(s.service)}</small></td><td><span class="badge ${s.healthy?'':'red'}">${s.healthy?s.latency_ms>=500?'SLOW':'HEALTHY':'UNAVAILABLE'}</span></td><td>${m.latency_ms} ms</td><td>${m.error_rate}%</td><td>${s.simulated_provider?'SIMULATED PROVIDER':'Local HTTP service'}</td></tr>`}).join('')}</tbody></table></div><div class="notice">Availability and latency are different checks. A service may respond successfully while taking too long.</div>`}
function lab(){return head('Break a dependency. Learn the boundary.','These controls change backend behavior. They do not send an answer to IncidentCommander.','CONTROLLED EXPERIMENTS')+`<div class="grid">${[['knowledge','Knowledge API failure','Knowledge retrieval returns HTTP 500. Both chat and voice lose required context.'],['stt','STT high latency','Recognition takes 2.4 seconds. Voice is slow; chat bypasses STT.'],['tts','TTS failure','Text generation succeeds, but speech delivery returns HTTP 503.'],['prompt','Bad prompt deployment','A changed prompt version creates invalid output. Dependency health stays available.']].map(([id,title,desc])=>`<article class="card experiment"><div class="card-body"><span class="eyebrow">${id==='tts'?'HERO SCENARIO':'SANDBOX FAULT'}</span><h2>${title}</h2><p>${desc}</p><button data-inject="${id}" ${running?'disabled':''}>${id==='prompt'?'Deploy configuration':'Inject failure'} ↗</button></div></article>`).join('')}</div><div class="notice">After injection, run two affected conversations so Commander observes repeated degradation. For TTS, use Voice. Try Chat too to demonstrate the unaffected channel.</div><div class="card"><div class="card-body"><h2>Judge-editable configuration</h2><p class="source-path" style="margin:14px 0">${esc(state?.source_path)}</p><p class="muted">Save a supported configuration change; the shared source watcher reloads it and exposes the real local diff.</p><button data-reset style="margin-top:20px">Restore healthy baseline</button></div></div>`}
function render(){const fn={playground,voice:playground,overview,conversations:history,knowledge,status:systemStatus,lab}[current];$('#main').innerHTML=fn();$('#breadcrumb').textContent=pageNames[current];document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===current))}
function updatePipeline(){$('#conversationSpace').innerHTML=conversationHTML();$('#pipelineBody').innerHTML=pipeline();$('#pipelineBadge').textContent=running?'RUNNING':result?.ok?'COMPLETED':'FAILED';$('#pipelineBadge').classList.toggle('red',!!result&&!result.ok)}
async function send(){if(running)return;question=$('#question').value.trim();if(!question)return;running=true;result=null;job=null;render();try{const started=await api('api/conversations',{channel,text:question});job=started;const end=Date.now()+30000;while(Date.now()<end){job=await api('api/jobs/'+started.request_id);if(job.status!=='running'){result=job.result;break}if(current==='playground'||current==='voice')updatePipeline();await new Promise(resolve=>setTimeout(resolve,250))}if(!result)throw Error('Request is still pending. Check Conversations for the eventual result.')}catch(e){toast(e.message)}finally{running=false;await refresh();render()}}
async function refresh(){try{state=await api('api/state');if(state.commander_url)$('#commanderLink').href=state.commander_url;$('#connection').textContent='● Services connected';$('#connection').className='connection';if(!['playground','voice'].includes(current)&&!$('#dialog').open)render()}catch{$('#connection').textContent='Service connection lost';$('#connection').className='connection bad'}}
function modal(title,text,actions){$('#dialogBody').innerHTML=`<h2>${title}</h2><p>${text}</p><div class="dialog-actions"><button data-close>Cancel</button>${actions||''}</div>`;$('#dialog').showModal()}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.id==='themeToggle'){const v=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=v;localStorage.setItem('converselab-theme',v);themeLabel()}
 if(b.dataset.nav){if($('#question'))question=$('#question').value;current=b.dataset.nav;if(current==='voice'){channel='voice';result=null;job=null}render()}
 if(b.dataset.channel){question=$('#question').value;channel=b.dataset.channel;result=null;job=null;render()}
 if(b.dataset.question){question=b.dataset.question;$('#question').value=question;$('#question').focus()}
 if(b.dataset.document){const d=documents.find(d=>d.id===b.dataset.document);modal(esc(d.title),esc(d.text),'')}
 if(b.dataset.result){result=state.events.find(r=>r.request_id===b.dataset.result);channel=result.channel;job=null;current='playground';render()}
 if(b.dataset.inject)modal('Launch this local experiment?','This changes actual service configuration. Run conversations afterward to observe the resulting behavior.',`<button class="primary" data-confirm-inject="${b.dataset.inject}">Inject experiment</button>`);
 if(b.hasAttribute('data-reset'))modal('Restore healthy configuration?','This overwrites local demo configuration edits and clears ConverseLab recent runtime activity. It does not erase Commander incident reports.','<button class="primary" data-confirm-inject="reset">Restore baseline</button>');
 if(b.hasAttribute('data-close'))$('#dialog').close();
 if(b.dataset.confirmInject){b.disabled=true;try{await api('control',{action:b.dataset.confirmInject});$('#dialog').close();await refresh();toast('Configuration updated. Send a fresh conversation to observe the result.')}catch(e){toast(e.message);b.disabled=false}}
});
document.addEventListener('submit',e=>{if(e.target.id==='conversationForm'){e.preventDefault();send()}});
$('#commanderLink').href='http://127.0.0.1:'+(Number(location.port)-10)+'/?application_id=converselab';
api('api/knowledge').then(v=>{documents=v.documents});refresh().then(render);setInterval(refresh,2000);
